apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-appsettings
  labels:
    courselabs: project3
stringData:
  config.json: |-
    {
      "ConnectionStrings": {
        {{- if .Values.include.sqlServer }}
        "ToDoDb": "Data Source={{ .Release.Name }}-db;Integrated Security=False;User Id=sa;Password={{ .Values.credentials.sqlServer.password }};MultipleActiveResultSets=True",
        {{- else }}
        "ToDoDb": "{{ .Values.connectionStrings.sqlServer }}",
        {{- end }}
        {{- if .Values.include.redis }}
        "Redis" : "{{ .Release.Name }}-queue:6379"
        {{- else }}
        "Redis": "{{ .Values.connectionStrings.redis }}",
        {{- end }}     
      },
      "Serilog": {
        "WriteTo": [
          {
            "Name": "AzureTableStorage",
            "Args": {
              "storageTableName": "logs",
              {{- if .Values.include.azurite }}
              "connectionString": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://{{ .Release.Name }}-storage:10002/devstoreaccount1;"
              {{- else }}
              "connectionString": "{{ .Values.connectionStrings.tableStorage }}"
              {{- end }}              
            }
          }
        ]
      }
    }