apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    courselabs: project3
spec:
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: 80
  selector:    
    app: {{ .Release.Name }}
    component: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    courselabs: project3
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: web
    spec:
      containers:
        - name: app
          image: {{ .Values.images.web }}
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-appsettings