apiVersion: v1
kind: Service
metadata:
  name: todo-db
  labels:
    courselabs: project3
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:    
    app: todo-list
    component: db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  labels:
    courselabs: project3
spec:
  selector:
    matchLabels:
      app: todo-list
      component: db
  template:
    metadata:
      labels:
        app: todo-list
        component: db
    spec:
      containers:
        - name: app
          image: mcr.microsoft.com/azure-sql-edge
          env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: MSSQL_PID
            value: 'Developer'
          - name: MSSQL_SA_PASSWORD
            value: 'AzureD3v!!!'
