apiVersion: v1
kind: Service
metadata:
  name: todo-web
  labels:
    courselabs: project3
spec:
  ports:
    - port: 8021
      targetPort: 80
  selector:    
    app: todo-list
    component: web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
  labels:
    courselabs: project3
spec:
  selector:
    matchLabels:
      app: todo-list
      component: web
  template:
    metadata:
      labels:
        app: todo-list
        component: web
    spec:
      containers:
        - name: app
          image: courselabs/todo-list-web:2211
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: todo-list-appsettings